// <auto-generated />
namespace Blog.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addIsAuthorized : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addIsAuthorized));
        
        string IMigrationMetadata.Id
        {
            get { return "201407062030195_addIsAuthorized"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
