// <auto-generated />
namespace Blog.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addTitle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTitle));
        
        string IMigrationMetadata.Id
        {
            get { return "201407081506193_addTitle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
